env:
    es2021: true
    node: true

overrides:
    - files:
          - '*.js'
          - '*.cjs'
      extends:
          - standard
          - eslint:recommended
          - prettier

    - files:
          - '*.ts'
      extends:
          - standard-with-typescript
          - eslint:recommended
          - plugin:@typescript-eslint/recommended
          - prettier
      plugins:
          - '@typescript-eslint'
      parser: '@typescript-eslint/parser'
      parserOptions:
          ecmaVersion: latest
          sourceType: module
      rules:
          '@typescript-eslint/strict-boolean-expressions': 'error'
          '@typescript-eslint/no-explicit-any':
              - error
              - fixToUnknown: true
          '@typescript-eslint/naming-convention':
              - error
              - leadingUnderscore: allowSingleOrDouble
