env:
    es2021: true
    node: true
extends:
    - standard-with-typescript
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier
plugins:
    - '@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
rules:
    '@typescript-eslint/strict-boolean-expressions': 'error'
    '@typescript-eslint/no-explicit-any':
        - error
        - fixToUnknown: true
